version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Thaitinh2004!
      MYSQL_DATABASE: crawled_data
      MYSQL_USER: root
      MYSQL_PASSWORD: Thaitinh2004!
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  scrapy:
    build: .
    command: scrapy crawl site2_crawler -o output2.csv
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app/myproject
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Thaitinh2004!
      - MYSQL_DATABASE=crawled_data