version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Thaitinh2004!
      MYSQL_DATABASE: crawled_data
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  scrapy:
    build: .
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy